---

  - name: Installing Glance
    apt:
      name: glance
      state: present
      update_cache: yes

  - name: Restarting Glance Services
    service:
      name: glance-api
      state: restarted
      enabled: yes
