---

  - name: Installing Nova
    apt:
      name:
        - nova-compute
        - python3-openstackclient
      state: present
      update_cache: yes

  - name: Restarting Nova
    service:
       name: nova-compute
       state: restarted
       enabled: yes
